<?php

/**
 * @file
 * Contains demo_content_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function demo_content_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the demo_content_entity module.
    case 'help.page.demo_content_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demonstrates the creation of a custom Content Entity') . '</p>';
      return $output;

    default:
  }
}
