<?php

/**
 * @file
 * Contains custom_config_form_ex.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_config_form_ex_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_config_form_ex module.
    case 'help.page.custom_config_form_ex':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_config_form_ex_theme() {
  return [
    'custom_config_form_ex' => [
      'render element' => 'children',
    ],
  ];
}
