<?php

/**
 * @file
 * Contains demo_entity_type.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function demo_entity_type_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the demo_entity_type module.
    case 'help.page.demo_entity_type':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo for creating a custom entity type (Content/Config)') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function demo_entity_type_theme() {
  return [
    'demo_entity_type' => [
      'render element' => 'children',
    ],
  ];
}
